"""Optional LLM-enhanced code improvement using Anthropic Claude."""

from __future__ import annotations

from mfp.config import MFPConfig
from mfp.errors import CompileError
from mfp.utils.logging import get_logger

logger = get_logger(__name__)

_ENHANCE_PROMPT = """\
You are a Python code reviewer. The following code was auto-generated by MFP from a Swagger/OpenAPI specification.
Improve it by:
1. Adding clearer, more descriptive parameter and return type annotations
2. Improving docstrings with better descriptions (keep Args/Returns format)
3. Renaming cryptic parameter names to human-readable ones
4. Adding validation checks where helpful
5. Keeping all functional logic IDENTICAL — do NOT change the HTTP calls, URLs, or behavior

Return ONLY the improved Python source code, no explanations or markdown.

CODE:
{code}
"""


async def enhance_with_llm(code: str, server_name: str, config: MFPConfig) -> str:
    """Optionally improve generated code using an LLM.

    This is an optional enhancement step that passes generated code through
    Claude to improve docstrings and type annotations. The functional behavior
    is never changed.

    Args:
        code: Generated Python source code.
        server_name: Server name for logging context.
        config: MFP configuration (needs llm_api_key and llm_model).

    Returns:
        Improved Python source code, or original code on failure.

    Raises:
        CompileError: If LLM enhancement is requested but API key is missing.
    """
    if not config.llm_api_key:
        raise CompileError("LLM enhancement requires MFP_LLM_API_KEY to be set")

    try:
        import anthropic  # noqa: PLC0415

        client = anthropic.Anthropic(api_key=config.llm_api_key)
        message = client.messages.create(
            model=config.llm_model,
            max_tokens=8192,
            messages=[{"role": "user", "content": _ENHANCE_PROMPT.format(code=code)}],
        )
        enhanced = str(message.content[0].text).strip()  # type: ignore[union-attr]
        logger.info("llm_enhanced", server=server_name, original_size=len(code), enhanced_size=len(enhanced))
        return enhanced

    except ImportError as exc:
        raise CompileError("anthropic package required for LLM enhancement: pip install mfp[llm]") from exc
    except Exception as exc:  # noqa: BLE001
        logger.warning("llm_enhance_failed", server=server_name, error=str(exc))
        return code  # Fall back to original generated code
