"""Optional LLM-enhanced code improvement using LiteLLM (supports OpenAI, Gemini, Anthropic, OpenRouter, etc.)."""

from __future__ import annotations

from mfp.config import MFPConfig
from mfp.errors import CompileError
from mfp.utils.logging import get_logger

logger = get_logger(__name__)

_ENHANCE_PROMPT = """\
You are a Python code reviewer. The following code was auto-generated by MFP from a Swagger/OpenAPI specification.
Improve it by:
1. Adding clearer, more descriptive parameter and return type annotations
2. Improving docstrings with better descriptions (keep Args/Returns format)
3. Renaming cryptic parameter names to human-readable ones
4. Adding validation checks where helpful
5. Keeping all functional logic IDENTICAL — do NOT change the HTTP calls, URLs, or behavior

Return ONLY the improved Python source code, no explanations or markdown.

CODE:
{code}
"""


async def enhance_with_llm(code: str, server_name: str, config: MFPConfig) -> str:
    """Optionally improve generated code using any LLM supported by LiteLLM.

    Uses `litellm.completion()` under the hood, which supports OpenAI, Gemini,
    Anthropic, OpenRouter, Azure, Cohere, and many other providers through a
    unified interface.  The model string in ``MFP_LLM_MODEL`` must follow
    LiteLLM's naming convention, e.g.:

    * OpenAI         → ``openai/gpt-4o``
    * Anthropic      → ``anthropic/claude-3-5-sonnet-20241022``
    * Google Gemini  → ``gemini/gemini-2.0-flash``
    * OpenRouter     → ``openrouter/mistralai/mistral-7b-instruct``

    ``MFP_LLM_API_KEY`` is forwarded as-is; for OpenRouter set it to your
    ``sk-or-*`` key.

    Args:
        code: Generated Python source code.
        server_name: Server name for logging context.
        config: MFP configuration (needs llm_api_key and llm_model).

    Returns:
        Improved Python source code, or original code on failure.

    Raises:
        CompileError: If LLM enhancement is requested but API key is missing,
            or if the ``litellm`` package is not installed.
    """
    if not config.llm_api_key:
        raise CompileError("LLM enhancement requires MFP_LLM_API_KEY to be set")

    try:
        import litellm  # noqa: PLC0415

        # litellm picks up the key via its own env-var logic, but we also
        # pass it explicitly so it works regardless of env-var naming.
        response = litellm.completion(
            model=config.llm_model,
            api_key=config.llm_api_key,
            messages=[{"role": "user", "content": _ENHANCE_PROMPT.format(code=code)}],
            max_tokens=8192,
        )
        enhanced: str = response.choices[0].message.content.strip()  # type: ignore[union-attr]
        logger.info(
            "llm_enhanced",
            server=server_name,
            model=config.llm_model,
            original_size=len(code),
            enhanced_size=len(enhanced),
        )
        return enhanced

    except ImportError as exc:
        raise CompileError(
            "litellm package required for LLM enhancement: pip install mfp[llm]"
        ) from exc
    except Exception as exc:  # noqa: BLE001
        logger.warning("llm_enhance_failed", server=server_name, model=config.llm_model, error=str(exc))
        return code  # Fall back to original generated code
