"""Unit tests for the code generator module."""

from __future__ import annotations

from typing import TYPE_CHECKING

from mce.compiler.codegen import CodeGenerator

if TYPE_CHECKING:
    from mce.models import ServerSpec


def test_generate_produces_valid_python(sample_server_spec: ServerSpec) -> None:
    """Generated code should be valid Python syntax."""
    import ast  # noqa: PLC0415

    gen = CodeGenerator()
    code = gen.generate(sample_server_spec)

    # Should parse without errors
    ast.parse(code)


def test_generated_code_contains_function_name(sample_server_spec: ServerSpec) -> None:
    """Generated code contains the expected function definition."""
    gen = CodeGenerator()
    code = gen.generate(sample_server_spec)

    assert "def get_current_weather" in code


def test_generated_code_contains_base_url_env(sample_server_spec: ServerSpec) -> None:
    """Generated code reads BASE_URL from environment variable."""
    gen = CodeGenerator()
    code = gen.generate(sample_server_spec)

    assert "MCE_WEATHER_BASE_URL" in code
    assert 'os.environ["MCE_WEATHER_BASE_URL"]' in code


def test_generated_code_never_hardcodes_credentials(sample_server_spec: ServerSpec) -> None:
    """Auth tokens must not appear as hardcoded strings in generated code."""
    gen = CodeGenerator()
    code = gen.generate(sample_server_spec)

    # No hardcoded token strings
    assert "Bearer " not in code or "AUTH" in code


def test_generated_code_has_httpx_import(sample_server_spec: ServerSpec) -> None:
    """Generated code imports httpx for HTTP calls."""
    gen = CodeGenerator()
    code = gen.generate(sample_server_spec)

    assert "import httpx" in code


def test_generated_code_required_param_in_signature(sample_server_spec: ServerSpec) -> None:
    """Required parameter 'city' appears in function signature without default."""
    gen = CodeGenerator()
    code = gen.generate(sample_server_spec)

    # city is required, should appear without None default
    assert "city: str" in code


def test_generated_code_optional_param_has_default(sample_server_spec: ServerSpec) -> None:
    """Optional parameter 'units' appears with a default value."""
    gen = CodeGenerator()
    code = gen.generate(sample_server_spec)

    assert "units" in code
    assert "None" in code  # Optional params use None default


def test_generated_code_has_docstring(sample_server_spec: ServerSpec) -> None:
    """Generated function has a docstring."""
    gen = CodeGenerator()
    code = gen.generate(sample_server_spec)

    assert '"""' in code or "'''" in code


def test_generator_banner_comment(sample_server_spec: ServerSpec) -> None:
    """Generated file has a banner indicating it was auto-generated."""
    gen = CodeGenerator()
    code = gen.generate(sample_server_spec)

    assert "GENERATED BY MCE" in code or "Auto-generated" in code


def test_safe_name_camel_case() -> None:
    """camelCase parameter names are converted to snake_case."""
    from mce.compiler.codegen import _safe_name  # noqa: PLC0415

    assert _safe_name("dashboardId") == "dashboard_id"
    assert _safe_name("orgId") == "org_id"
    assert _safe_name("folderId") == "folder_id"
    assert _safe_name("panelId") == "panel_id"


def test_safe_name_already_snake_case() -> None:
    """Already-snake_case names pass through unchanged."""
    from mce.compiler.codegen import _safe_name  # noqa: PLC0415

    assert _safe_name("city") == "city"
    assert _safe_name("start_time") == "start_time"
